src/api/routes.py
from flask import Blueprint, redirect, request, jsonify, render_template, session, url_for
from db import Personnel, Event, TimeTable, db
import cloudinary
from cloudinary.utils import cloudinary_url
import secrets
from init import bcrypt
import json
import hashlib
import os
import qrcode
from datetime import datetime



def generate_8_digit_hash(value):
	return hashlib.md5(str(value).encode()).hexdigest()[:8]



####### GENERAL ROUTES #######
# Combine all the general routes into a single blueprint
general_bp = Blueprint('general_routes', __name__)
@general_bp.route('/ping')
def ping():
	print('\033[92m + Pong\033[0m')
	return 'Pong', 200

@general_bp.route('/exit')
def exit():
	session.clear()
	db.session.remove()
	print('\033[93m - Session cleared successfully\033[0m')
	quit()

@general_bp.route('/dashboard')
def dashboard():
	total_employees = Personnel.query.filter_by(deleted=False).count()
	return render_template('dashboard.html', total_employees= total_employees, page='dashboard')

####### EMPLOYEE ROUTES #######
# Combine all the employee routes into a single blueprint
employee_bp = Blueprint('employee_routes', __name__)

## EMPLOYEES ##
@employee_bp.route('/manage-employees')
def manage_employees():
	employees = Personnel.query.filter_by(deleted=False).all()
	return render_template('manage.html', employees=employees, cloudinary_url=cloudinary_url, page='employees')


@employee_bp.route('/add-employee', methods=['POST', 'GET'])
def add_employee():
	if request.method == 'POST':
		print('\033[94m - POST: Adding employee\033[0m')
		
		cin = request.form.get('cin')
		if Personnel.query.filter_by(cin=cin).first():
			print('\033[91m - Employee with CIN already exists\033[0m')
			return {'success': False, 'message': 'Employee with CIN already exists'}, 400
		
		email = request.form.get('email')
		if Personnel.query.filter_by(email=email).first():
			print('\033[91m - Employee with email already exists\033[0m')
			return {'success': False, 'message': 'Employee with email already exists'}, 400
		
		first_name = request.form.get('first_name')
		last_name = request.form.get('last_name')
		phone = request.form.get('phone')
		password = secrets.token_hex(8)
		shift = request.form.get('shift')

		# Generate a unique registration number based on the CIN
		# This is done by hashing the CIN, then converting it to hexadecimal to get a unique employee number
		# The first 8 characters of the hash are used as the registration number
		reg_num = generate_8_digit_hash(cin)

		photo = request.files.get('photo')
		if not photo:
			print('\033[91m - No photo provided\033[0m')
			return {'success': False, 'message': 'No photo provided'}, 400

		# Generate a unique ID for the photo to avoid conflicts
		# Cloudinary keeps cached versions of images, which may cause the image not to update
		# The photo ID should be unique and independent of the employee number
		photo_id = generate_8_digit_hash(secrets.token_hex(8))

		# Save the image to cloudinary
		res = cloudinary.uploader.upload(photo, public_id = photo_id)
		print('\033[94m + Image uploaded successfully to cloudinary: ', res['url'], '\033[0m')

		# Insert the employee data
		db.session.add(Personnel(
			reg_num=reg_num,
			cin=cin,
			photo=photo_id,

			first_name=first_name,
			last_name=last_name,
			phone=phone,
			email=email,
			password=bcrypt.generate_password_hash(password).decode('utf-8'),
			shift=shift,

			deleted=False,
			is_admin=False
		))
		try:
			db.session.commit()
			print('\033[94m + Employee added successfully\033[0m')
			return {'success': True, 'message': 'Employee added successfully'}, 200
		except Exception as e:
			print('\033[91m - Error adding employee: ', e, '\033[0m')
			return {'success': False, 'message': 'Error adding employee'}, 500
	else:
		print('\033[94m - GET: Showing add employee form\033[0m')
		return render_template('add.html', page='employees')

@employee_bp.route('/edit-employee-details/<cin>', methods=['POST', 'GET'])
def edit_employee_details(cin):
	employee = Personnel.query.filter_by(cin=cin).first()
	if request.method == 'POST':
		print('\033[94m - POST: Editing employee\033[0m')

		# Check if the CIN has been changed
		new_cin = request.form.get('cin')
		if new_cin != cin and Personnel.query.filter_by(cin=new_cin).first():
			print('\033[91m - Employee with CIN already exists\033[0m')
			return {'success': False, 'message': 'Employee with CIN already exists'}, 400
		
		email = employee.email
		new_email = request.form.get('email')
		if new_email != email and Personnel.query.filter_by(email=new_email).first():
			print('\033[91m - Employee with email already exists\033[0m')
			return {'success': False, 'message': 'Employee with email already exists'}, 400
		
		first_name = request.form.get('first_name')
		last_name = request.form.get('last_name')
		phone = request.form.get('phone')
		shift = request.form.get('shift')

		photo = request.files.get('photo')
		if photo:
			# Generate a unique ID for the photo to avoid conflicts
			# Cloudinary keeps cached versions of images, which may cause the image not to update
			# The photo ID should be unique and independent of the employee number
			photo_id = generate_8_digit_hash(secrets.token_hex(8))

			# Save the image to cloudinary
			res = cloudinary.uploader.upload(photo, public_id = photo_id)
			print('\033[94m + Image uploaded successfully to cloudinary: ', res['url'], '\033[0m')

			employee.photo = photo_id

		employee.cin = new_cin
		employee.first_name = first_name
		employee.last_name = last_name
		employee.phone = phone
		employee.email = email
		employee.shift = shift

		try:
			db.session.commit()
			print('\033[94m + Employee edited successfully\033[0m')
			return {'success': True, 'message': 'Employee edited successfully'}, 200
		except Exception as e:
			print('\033[91m - Error editing employee: ', e, '\033[0m')
			return {'success': False, 'message': 'Error editing employee'}, 500
	else:
		print('\033[94m - GET: Showing edit employee form\033[0m')
		return render_template('edit.html', employee=employee, cloudinary_url=cloudinary_url, page='employees')

@employee_bp.route('/statistics/<cin>', methods=['POST', 'GET'])
def statistics(cin):
    employee = Personnel.query.filter_by(cin=cin).first()
    if request.method == 'POST':
        # Handle POST request if needed
        pass
    else:
        return render_template('stat.html', employee=employee, cloudinary_url=cloudinary_url, page='employees')

@employee_bp.route('/delete-employee/<cin>', methods=['POST'])
def delete_employee(cin):
	employee = Personnel.query.filter_by(cin=cin).first()
	employee.deleted = True
	try:
		db.session.commit()
		print('\033[94m + Employee deleted successfully\033[0m')
		return {'success': True, 'message': 'Employee deleted successfully'}, 200
	except Exception as e:
		print('\033[91m - Error deleting employee: ', e, '\033[0m')
		return {'success': False, 'message': 'Error deleting employee'}, 500
	
@employee_bp.route('/restore-employee/<cin>', methods=['POST'])
def restore_employee(cin):
	employee = Personnel.query.filter_by(cin=cin).first()
	employee.deleted = False
	try:
		db.session.commit()
		print('\033[94m + Employee restored successfully\033[0m')
		return {'success': True, 'message': 'Employee restored successfully'}, 200
	except Exception as e:
		print('\033[91m - Error restoring employee: ', e, '\033[0m')
		return {'success': False, 'message': 'Error restoring employee'}, 500

@employee_bp.route('/trash-bin')
def trash():
	employees = Personnel.query.filter_by(deleted=True).all()
	return render_template('trash.html', employees=employees, cloudinary_url=cloudinary_url, page='trash')
@employee_bp.route('/permanent-delete-employee/<cin>', methods=['POST'])
def permanent_delete_employee(cin):
    employee = Personnel.query.filter_by(cin=cin).first()
    if employee:
        try:
            # Manually delete related timetable entries
            TimeTable.query.filter_by(personnel_reg_num=employee.reg_num).delete()

            # Now delete the employee
            db.session.delete(employee)
            db.session.commit()
            print('\033[94m + Employee permanently deleted successfully\033[0m')
            return {'success': True, 'message': 'Employee permanently deleted successfully'}, 200
        except Exception as e:
            db.session.rollback()  # Rollback in case of error
            print('\033[91m - Error permanently deleting employee: ', e, '\033[0m')
            return {'success': False, 'message': 'Error permanently deleting employee'}, 500
    else:
        return {'success': False, 'message': 'Employee not found'}, 404


## TIMETABLE ##
@employee_bp.route('/edit-employee-timetable/<personnel_reg_num>', methods=['GET', 'POST'])
def edit_employee_timetable(personnel_reg_num):
    employee = Personnel.query.filter_by(reg_num=personnel_reg_num).first()

    if not employee:
        return jsonify({'success': False, 'message': 'Employee not found'}), 404

    if request.method == 'POST':
        timetable_json = request.form.get('timetable_json')

        if not timetable_json:
            return jsonify({'success': False, 'message': 'No timetable data provided'}), 400

        try:
            timetable_data_list = json.loads(timetable_json)
            existing_employee = TimeTable.query.filter_by(personnel_reg_num=personnel_reg_num).first()
            existing_timetable = json.loads(existing_employee.json) if existing_employee else {}

            for timetable_data in timetable_data_list:
                add_time(timetable_data, existing_timetable, personnel_reg_num)

            db.session.commit()
            return jsonify({'success': True, 'message': 'Entry added successfully'}), 200
        except Exception as e:
            print(f'Error committing timetable data: {e}')
            db.session.rollback()
            return jsonify({'success': False, 'message': 'Error adding TimeTable'}), 500
    else:

src/api/templates/add.html
{% extends 'base.html' %}

{% block title %}Add Employee{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/add.css') }}">
{% endblock %}

{% block content %}
<h2>Add Employee</h2>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<ul class="flashes">
	{% for category, message in messages %}
	<li class="{{ category }}">{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}
{% endwith %}
<div class="container1">

<form class="row g-3 needs-validation" id="add-employee-form" method="POST" novalidate>
	<div class="col-md-4 form-group">
		<label for="first-name" class="form-label">First name</label>
		<input type="text" class="form-control text-field" id="first-name" placeholder="First name" pattern="[A-Za-z]{3,}"
			name="first_name" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid first name.
		</div>
	</div>
	<div class="col-md-4 form-group">
		<label for="last-name" class="form-label">Last name</label>
		<input type="text" class="form-control text-field" id="last-name" placeholder="Last name" pattern="[A-Za-z]{3,}"
			name="last_name" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid last name.
		</div>
	</div>
	<div class="col-md-4 form-group">
		<label for="cin" class="form-label">CIN</label>
		<input type="text" class="form-control text-field" id="cin" placeholder="CIN" pattern="[A-Z]{1,2}[0-9]{6}" name="cin"
			required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid CIN. (e.g. AA123456)
		</div>
	</div>

	<div class="col-md-7 form-group">
		<label for="email" class="form-label">Email</label>
		<input type="email" class="form-control text-field" id="email" placeholder="Email" name="email" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid email address.
		</div>
	</div>
	<div class="col-md-5 form-group">
		<label for="phone" class="form-label">Phone</label>
		<input type="text" class="form-control text-field" id="phone" placeholder="Phone" pattern="[0-9]{10}" name="phone"
			required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid phone number. (Moroccan phone number)
		</div>
	</div>

	<div class="col-md-4 form-group">
		<label for="shift" class="form-label">Shift Type</label>
		<select class="form-select text-field" id="shift" name="shift" required>
			<option value="" selected disabled>Select a shift type</option>
			<option value="normal">Normal Shift</option>
			<option value="split">Split Shift</option>
			<option value="rotating">Rotating Shift</option>
		</select>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please select a shift type.
		</div>
	</div>
	<div class="col-md-8 form-group">
		<label for="photo" class="form-label">Photo</label>
		<input type="file" class="form-control text-field" id="photo" accept="image/*" name="photo" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please upload a valid profile photo. (It should be high quality and clear)
		</div>
	</div>

	<div class="col-12 form-group">
		<button class="btn submit-button" type="submit">Submit</button>
	</div>
</form>

<!--<form action="" method="POST" enctype="multipart/form-data">
	<div class="form-group">
		<label for="cin">CIN</label>
		<input type="text" id="cin" name="cin" placeholder="Enter the employee's CIN" required>
	</div>
	<div class="form-group">
		<label for="last-name">Last Name</label>
		<input type="text" id="last-name" name="last_name" placeholder="Enter the employee's last name" required>
	</div>
	<div class="form-group">
		<label for="first-name">First Name</label>
		<input type="text" id="first-name" name="first_name" placeholder="Enter the employee's first name" required>
	</div>
	<div class="form-group">
		<label for="function">Fonction</label>
		<input type="text" id="function" name="function" placeholder="Enter the employee's function" required>
	</div>
	<div class="form-group">
		<label for="email">Email</label>
		<input type="email" id="email" name="email" placeholder="Enter the employee's email address" required>
	</div>
	<div class="form-group">
		<label for="phone">Phone</label>
		<input type="text" id="phone" name="phone" placeholder="Enter the employee's phone number" required>
	</div>
	<div class="form-group">
		<label for="type">Type</label>
		<input type="text" id="type" name="type" placeholder="Enter the employee's type" required>
	</div>
	<div class="form-group">
		<label for="photo">Photo</label>
		<input type="file" id="photo" name="photo" required>
	</div>
	<button type="submit" class="submit-button">Submit</button>
</form>-->
</div>
{% endblock content %}

{% block scripts %}
{% endblock %}

src/api/templates/cameras.html
{% extends 'base.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/camera.css') }}">
{% endblock %}

{% block content %}
<div class="body">
    {% for i in range(1, 7) %}
    <div class="camWidget">
        <video autoplay class="camera-stream" id="cam{{ i }}" controls src="/camera/video_feed"></video>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/camera.js') }}"></script>
{% endblock %}

src/api/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<h1>Dashboard</h1>
<p>Welcome to the dashboard!</p>
<div class="line"></div>
<div class="d-flex justify-content-between align-items-center gap-2">
	<div class="card bg-primary text-white">
		<div class="card-body">
			<h5 class="card-title">Total Employees</h5>
			<p class="card-text">{{ total_employees }}</p> 
		</div>
	</div>
</div>

{% endblock %}

src/api/templates/edit.html
{% extends 'base.html' %}

{% block title %}Edit Employee - {{ employee.last_name }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/edit.css') }}">

<script>
	const employeeCIN = "{{ employee.cin }}";
	const employeeNum = "{{ employee.reg_num }}";
</script>
{% endblock %}

{% block content %}
<div class="links">
	<span>Edit Details</span>
	/
	<a href="{{ url_for('employee_routes.edit_employee_timetable', personnel_reg_num=employee.reg_num) }}">Edit Timetable</a>
</div>

<form class="container1 needs-validation form-group" id="edit-employee-form" method="POST" novalidate>
	<div class="col-md-4">
		<label for="first-name" class="form-label">First name</label>
		<input type="text " class="form-control text-field" id="first-name" placeholder="First name" pattern="[A-Za-z]{3,}"
			name="first_name" value="{{ employee.first_name }}" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid first name.
		</div>
	</div>
	<div class="col-md-4">
		<label for="last-name" class="form-label">Last name</label>
		<input type="text " class="form-control text-field" id="last-name" placeholder="Last name" pattern="[A-Za-z]{3,}"
			name="last_name" value="{{ employee.last_name }}" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid last name.
		</div>
	</div>
	<div class="col-md-4">
		<label for="cin" class="form-label">CIN</label>
		<input type="text " class="form-control text-field" id="cin" placeholder="CIN" pattern="[A-Z]{1,2}[0-9]{6}" name="cin"
			value="{{ employee.cin }}" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid CIN. (e.g. AA123456)
		</div>
	</div>

	<div class="col-md-7">
		<label for="email" class="form-label">Email</label>
		<input type="email" class="form-control text-field" id="email" placeholder="Email" name="email"
			value="{{ employee.email }}" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid email address.
		</div>
	</div>
	<div class="col-md-5">
		<label for="phone" class="form-label">Phone</label>
		<input type="text" class="form-control text-field" id="phone" placeholder="Phone" pattern="[0-9]{10}" name="phone"
			value="{{ employee.phone }}" required>
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please enter a valid phone number. (Moroccan phone number)
		</div>
	</div>

	<div class="col-md-4">
		<label for="shift" class="form-label">Shift Type</label>
		<select class="form-select text-field" id="shift" name="shift" required>
			<option value="normal" {% if employee.shift=="normal" %}selected{% endif %}>Normal Shift</option>
			<option value="split" {% if employee.shift=="split" %}selected{% endif %}>Split Shift</option>
			<option value="rotating" {% if employee.shift=="rotating" %}selected{% endif %}>Rotating Shift</option>
		</select>
	</div>
	<div class="col-md-6">
		<label for="photo" class="form-label ">Photo</label>
		<input type="file" class="form-control text-field" id="photo" accept="image/*" name="photo">
		<div class="valid-feedback">
			Looks good!
		</div>
		<div class="invalid-feedback">
			Please upload a valid image.
		</div>
	</div>
	<div class="col-md-2 ">
		<img src="{{ cloudinary_url(employee.photo)[0] }}" alt="Employee Photo" class="img-thumbnail">
	</div>

	<div class="col-12">
		<button class="btn submit-button" type="submit">Submit</button>
	</div>
</form>
{% endblock %}

src/api/templates/manage.html
{% extends 'base.html' %}

{% block title %}Manage Employees{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/manage.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block content %}
<div class="header">
	<h1>Manage Employees</h1>
	<a href="{{ url_for('employee_routes.add_employee') }}" class="add-employee btn-primary">Add Employee</a>
</div>
{% for employee in employees %}
<div class="employee-card">
	<img src="{{ cloudinary_url(employee.photo)[0] }}" alt="Profile Image" class="profile-image">
	<div class="employee-details">
		<h2>{{ employee.cin }}</h2>
		<p>{{ employee.last_name }} {{ employee.first_name }}</p>
		<div class="d-flex  justify-content-center">
			<a class="btn btn-primary"
				href="{{ url_for('employee_routes.edit_employee_details', cin=employee.cin, cloudinary_url=cloudinary_url) }}">Details</a>
			<a href="{{ url_for('employee_routes.statistics', cin=employee.cin) }}" class="btn btn-primary">Statistics</a>
		</div>

		<form action="{{ url_for('employee_routes.delete_employee', cin=employee.cin, cloudinary_url=cloudinary_url) }}"
			method="POST" style="display:inline;">
			<button type="submit" class="btn delete"><i class="fa fa-trash"></i></button>
		</form>
	</div>
</div>
{% endfor %}
{% endblock %}

src/api/templates/stat.html
{% extends 'base.html' %}

{% block title %}Employee Statistics{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stat.css') }}">
{% endblock %}

{% block content %}
<div class="statistics">
    <div class="stat">
        <h2>Absence</h2>
        <h3>15</h3>h
    </div>
    <div class="stat">
        <h2>Overtime</h2>
        <h3>60</h3>h
    </div>
    <div class="stat">
        <h2>Latetime</h2>
        <h3>3</h3>h
    </div>
</div>
{% endblock %}

src/api/templates/timetable.html
{% extends 'base.html' %}

{% block title %}Edit Employee - {{ employee.last_name }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/edit.css') }}">

<script>
	const employeeCIN = "{{ employee.cin }}";
	const employeeNum = "{{ employee.reg_num }}";
</script>
{% endblock %}

{% block content %}
<div class="links">
	<a href="{{ url_for('employee_routes.edit_employee_details', cin=employee.cin) }}">Edit Details</a>
	/
	<span>Edit Timetable</span>
</div>

<div class="table" id="timetable">
	<button onclick="handleADD_show()">Add</button>
	<div class="card" id="card" style="display: none;">
		<form method="POST" class="row g-3 needs-validation" id="add-timetable-form" novalidate onsubmit="addTimeTableToJson(event)"
			{#!action="{{ url_for('employee_routes.edit_employee_timetable', personnel_reg_num=employee.reg_num) }}" #}>
			<button type="button" id="back" class="back btn btn-primary" onclick="handleADD_hide()">Back</button>
			<h1>Add hours</h1>

			<div class="form-group col-md-4">
				<label for="day" class="form-label">Select the Day:</label>
				<select id="day" name="day" class="form-select" required>
					<option value="" selected disabled hidden>Select a day</option>
					<option value="Monday">Monday</option>
					<option value="Tuesday">Tuesday</option>
					<option value="Wednesday">Wednesday</option>
					<option value="Thursday">Thursday</option>
					<option value="Friday">Friday</option>
					<option value="Saturday">Saturday</option>
					<option value="Sunday">Sunday</option>
				</select>
				<div class="valid-feedback">
					Looks good!
				</div>
				<div class="invalid-feedback">
					Please select a day.
				</div>
			</div>

			<div class="form-group col-md-4">
				<label for="from" class="form-label">From:</label>
				<select class="form-select" id="from" name="from" required>
					<option value="" selected disabled hidden>Select a start time</option>
				</select>
				<div class="valid-feedback">
					Looks good!
				</div>
				<div class="invalid-feedback">
					Please select a start time.
				</div>
			</div>

			<div class="form-group col-md-4">
				<label for="to" class="form-label">To:</label>
				<select class="form-select" id="to" name="to" required>
					<option value="" selected disabled hidden>Select an end time</option>
				</select>
				<div class="valid-feedback">
					Looks good!
				</div>
				<div class="invalid-feedback">
					Please select an end time.
				</div>
			</div>

			<input type="hidden" name="timetable_json" id="timetable_json">
			<input type="submit" value="ADD" class="btn btn-primary">
		</form>
	</div>
	<table>
		<thead>
			<tr>
				<th>Time</th>
				{% for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
				<th class="day">{{ day }}</th>
				{% endfor %}
			</tr>
		</thead>
		<tbody>
			{% for i in range(24) %}
			<tr>
				<th>{{ '%02d:00-%02d:00'|format(i, i+1) }}</th>
				{% for day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %}
				<td id="{{ day }}-{{ '%02d'|format(i) }}"></td>
				{% endfor %}
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/timetable.js') }}" defer></script>
{% endblock %}

src/api/templates/trash.html
{% extends 'base.html' %}

{% block title %}Trash bin{% endblock %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/trash.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

{% endblock %}

{% block content %}
<div class="header">
	<h1>Trash Bin</h1>
</div>
<table class="styled-table">
	<thead>
		<tr>
			<th>Photo</th>
			<th>CIN</th>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		{% for employee in employees %}
		<tr>
			<td><img src="{{ cloudinary_url(employee.photo)[0] }}" alt="Profile Image" class="profile-image"></td>
			<td>{{ employee.cin }}</td>
			<td>{{ employee.first_name }}</td>
			<td>{{ employee.last_name }}</td>
			<td>
				<form action="{{ url_for('employee_routes.restore_employee', cin=employee.cin) }}" method="POST" style="display:inline;">
					<button type="submit" class="btn restore"><i class="fa-solid fa-rotate-left"></i></button>
				</form>
				<form action="{{ url_for('employee_routes.permanent_delete_employee', cin=employee.cin) }}" method="POST" style="display:inline;">
					<button type="submit" class="btn delete"><i class="fa-solid fa-trash"></i></button>

				</form>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}